### ISSUE TITLE
supported feature tags

### ISSUE THREAD

**Issue by Matthias84** [mkagenius/osm2maya#1]
Hi,
I linked your script at https://wiki.openstreetmap.org/wiki/3D
It would be great, if you could write some more details on which OSM tags you support etc.

**Comment by mkagenius** [comment]
Hi,

Thanks for the link to the wiki. I have added the supported tags here: 

https://github.com/mkagenius/osm2maya/blob/master/supported_tags.md

I will be updating it as the script gets modified to use more tags.
